name: Build and Push Docker Image

on:
  push:
    branches:
      - '**' # 匹配所有分支
    tags:
      - 'v*' # 在发布 tag (如 v1.0.0) 时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Docker Buildx（支持多平台和更高效的构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 提取版本号（从标签或分支名中）
      - name: Extract Docker Image Tag
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=$(date +%Y%m%d-%H%M%S)
          fi
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/your-repo-name:latest
            ${{ secrets.DOCKER_USERNAME }}/your-repo-name:${{ env.VERSION }}

      # 可选：清理构建缓存（减少占用空间）
      - name: Clean up Docker Cache
        run: docker builder prune -f
